USE ONG;

DROP TRIGGER IF EXISTS TRIGGER_ADOTADO;
DELIMITER //
CREATE TRIGGER TRIGGER_ADOTADO AFTER UPDATE ON ANIMAL
FOR EACH ROW
BEGIN
IF(NEW.ID_LOGIN IS NOT NULL) THEN
UPDATE LOGIN SET ID_PERMISSAO = 4 WHERE ID_LOGIN = NEW.ID_LOGIN;
END IF;
END;//
DELIMITER ; 

SHOW TRIGGERS;
/*							
INSERT INTO ANIMAL VALUES(1001, 'Snoop', 2, NULL, 'Vem com um passarinho de brinde', NULL, 100, NULL);

SELECT * FROM  ANIMAL WHERE ID_LOGIN IS NOT NULL AND DATA_ADOCAO IS NULL;
UPDATE ANIMAL SET DATA_ADOCAO = CURRENT_DATE(), ID_LOGIN = 3 WHERE ID_ANIMAL = 1000;


SELECT * FROM ANIMAL;
SELECT * FROM PERMISSAO;

SELECT * FROM LOGIN;


INSERT INTO LOGIN VALUES(3, 'Dumbledore', 424242, 'Hogwarts', '(16)99999999', 'dumbledore@gmail.com', 3);

*/